import { createElement } from 'lwc';
import HelloWorldSFTroop from 'c/helloWorldSFTroop';

describe('c-hello-world-sf-troop', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-hello-world-sf-troop', {
            is: HelloWorldSFTroop
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // In this section, you need to write your assertions to test the behavior of your component.
        // For example, if the component renders a div with some content, you can do something like:
        const div = element.shadowRoot.querySelector('div');
        expect(div.textContent).toBe('Expected Text'); // Modify 'Expected Text' to match the actual text content you expect
    });
});
